/*DATABASE SOCIALBAN*//*DATABASE SOCIALBAN*//*DATABASE SOCIALBAN*/
/*DATABASE SOCIALBAN*/
/*DATABASE SOCIALBAN*/
/*DATABASE SOCIALBAN*//*DATABASE SOCIALBAN*//*DATABASE SOCIALBAN*/
/*DATABASE SOCIALBAN*/
/*DATABASE SOCIALBAN*/
/*DATABASE SOCIALBAN*//*DATABASE SOCIALBAN*//*DATABASE SOCIALBAN*/
/*DATABASE SOCIALBAN*/
/*DATABASE SOCIALBAN*/
/*DATABASE SOCIALBAN*//*DATABASE SOCIALBAN*//*DATABASE SOCIALBAN*/

create database SocialBan;
use socialban;
show tables;
drop database SocialBan;
select * from user;
